### ISSUE TITLE
WildInspect wont show anything.

### ISSUE THREAD

**Issue by Firestone82** [OmerBenGera/WildInspect#3] opened 2021-03-09 07:24 UTC
Hi, when I click on chest or location where was block, by WildInspect it shows nothing, by CoreProtect it shows normally.
I have done some debugging and there must be and error somewhere, CoreProtectHook#parseResult returns data, but then it gets lost somewhere. Its always showing like there is no query. But there is.

By doing it, I have been broadcasting result from CoreProtectHook, that works normally, but then it gets lost somewhere.

Thanks for your help.

**Comment by OmerBenGera** [comment] 2021-03-09 10:19
Duplicate of #1

**Closed by OmerBenGera** 2021-03-09 10:19 UTC
